config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
   get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root "posts#index"

  get "myposts", to: "posts#myposts"
  get "preview", to: "export#preview"

  resources :posts do
    resources :comments
  end

  namespace :admin do
    get "myposts", to: "posts#myposts"
    resources :posts do
      resources :comments
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
  validates :post_date, presence: true
  validates :content, presence: true, length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :comments, dependent: :destroy
         has_many :posts, dependent: :destroy

end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :my_authenticate_user!

  def my_authenticate_user!
    authenticate_user! if current_user.admin
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::AdminController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.comment_date = Time.now
    if @comment.save
      redirect_to admin_post_path(@post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to admin_post_path(@post), status: :see_other
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :user_id)
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.post_date = Time.now
    if @post.save
      redirect_to [:admin, @post]
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.post_date = Time.now
    if @post.update(post_params)
      redirect_to [:admin, @post]
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path, status: :see_other
  end

  def myposts
    @myposts = Post.where(user_id: current_user)
  end

  private
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if current_user.admin
      admin_posts_path
    else
      posts_path
    end
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:nick, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:nick, :email, :password, :current_password)}
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.comment_date = Time.now
    if @comment.save
      redirect_to post_path(@post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post), status: :see_other
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :user_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    respond_to do |format|
      format.html do
        @post = Post.find(params[:id])
      end
      format.pdf do
        @post = Post.find(params[:id])
        render pdf: "file_name", template: "posts/show", layout: "pdf", formats: [:html]   # Excluding ".pdf" extension.

      end
    end
  end

  def new
    @post = Post.new
  end

  private
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/export_helper.rb
module ExportHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/My_blog/_header.html.erb
<nav class="navbar navbar-expand-lg bg-primary bg-gradient" style="font-family: 'Permanent Marker', cursive;">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if user_signed_in? && current_user.admin %>
      <%= link_to "MybloG", admin_posts_path, class:"navbar-brand fs-1" %>
    <% else %>
      <%= link_to "MybloG", root_path, class:"navbar-brand fs-1" %>
    <% end %>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
		  <ul class="navbar-nav">
        <% if user_signed_in? && current_user.admin %>
          <li class="mx-4 my-2">
            <%= link_to "Moje wpisy", admin_myposts_path, class:"text-dark text-decoration-none fs-4"  %>
          </li>
          <li class="mx-4 my-2">
            <%= link_to "Edytuj konto", edit_user_registration_path, class:"text-dark text-decoration-none fs-4"  %>
          </li>
          <li class="mx-4 my-2">
            <%= link_to "Wyloguj", destroy_user_session_path ,method: :delete, class:"text-dark text-decoration-none fs-4"  %>
          </li>
          <li class="mx-4">
            <h1 class="text-white">
              <%= current_user.nick %>
            </h1>
          </li>
        <% elsif user_signed_in? %>
          <li class="mx-4 my-2">
            <%= link_to "Edytuj konto", edit_user_registration_path, class:"text-dark text-decoration-none fs-4"  %>
          </li>
          <li class="mx-4 my-2">
            <%= link_to "Wyloguj", destroy_user_session_path ,method: :delete, class:"text-dark text-decoration-none fs-4"  %>
          </li>
          <li class="mx-4">
            <h1 class="text-white">
              <%= current_user.nick %>
            </h1>
          </li>
        <% else %>
          <li class="nav-item mx-4">
            <%= link_to "Stwórz konto", new_user_registration_path, class:"fs-3 text-dark text-decoration-none"  %>
          </li>
          <li class="nav-item mx-4">
            <%= link_to "Zaloguj", new_user_session_path, class:"fs-3 text-dark text-decoration-none"  %>
          </li>
        <% end %>
		  </ul>
		</div>
  </div>
</nav>

app/views/admin/comments/_comment.html.erb
<div class="card my-3 border border-primary">
  <div class="card-body">
    <h4 class="card-title text-muted d-inline ">
      <%= User.find(comment.user_id).nick %>
    </h4>
    <h4 class="text-muted float-end d-inline">
      <%= comment.comment_date.strftime("%k:%M %d/%m/%Y") %>
    </h4>
    <p class="card-text my-3">
      <%= comment.content %>
    </p>
    <%= link_to "Usuń komentarz", [:admin, comment.post, comment],class:"btn btn-warning float-end fs-6", data: {
                        turbo_method: :delete,
                        turbo_confirm: "Na pewno?"
                      } %>
  </div>
</div>
<br>

app/views/admin/comments/_form.html.erb
<%= form_with model: [:admin, @post, @post.comments.build ] do |f| %>

    <div class="d-flex justify-content-center">
      <%= f.text_area :content, size:"80x4", class:"form-control", placeholder: "Komentarz" %>
    </div>
      <%= f.number_field :user_id, id: :post_user_id, class:"form-control", value: current_user.id, type: :hidden%>
    <div class="text-center">
      <%= f.submit "Dodaj komentarz", class:"btn btn-warning fs-6 my-2" %>
    </div>

<% end %>

app/views/admin/posts/_form.html.erb
<%= form_with model: [:admin, @post] do |f| %>
  <div class="card-body">
    <%= f.text_field :title, class:"form-control", placeholder:"Tytuł" %>
    <% @post.errors.full_messages_for(:title).each do |msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    <br>
    <%= f.text_area :content, size: "70x10", class:"form-control", placeholder:"Treść" %>
    <% @post.errors.full_messages_for(:content).each do |msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    <br>
    <%= f.number_field :user_id, id: :post_user_id, class:"form-control", value: current_user.id, type: :hidden%>
  </div>
  <div class="card-footer text-muted bg-primary bg-gradien">
    <%= f.submit "Stwórz", class:"btn btn-warning fs-4"%>
  </div>
<% end %>

app/views/admin/posts/_post.html.erb
<div class="card" style="font-family: 'Peralta', cursive;">
  <div class="card-header bg-primary bg-gradien fs-3 text-white">
    <%= post.title %>
  </div>
  <div class="card-body">
    <p class="card-text fs-5">
      <%= post.content %>
    </p>
  </div>
  <div class="card-footer text-muted">
    <p class="d-inline mx-3 fs-5">
      <%= User.find(post.user_id).nick %>
    </p>
    <p class="d-inline mx-3 fs-5">
      <%= post.post_date.strftime("%k:%M %d/%m/%Y") %>
    </p>

    <%= link_to "Wiecej...", admin_post_path(post.id), class:"d-inline btn btn-warning float-end fs-6" %>
  </div>
</div>
<br>

app/views/admin/posts/edit.html.erb
<br>
<div class="container" style="font-family: 'Anton', sans-serif; width: 900px;">
  <div class="card text-center">
    <div class="card-header bg-primary bg-gradien text-black fs-2">
      <h1> Edytuj Post </h1>
    </div>
    <%= render "form", post: @post %>
  </div>
</div>

app/views/admin/posts/index.html.erb
<div class="container" style="font-family: 'Peralta', cursive;">
  <div class="my-3">
    <h1 class="d-inline">Aktualne Wpisy</h1>
    <%= link_to " + Dodaj nowy", new_admin_post_path, class:"btn btn-warning float-end fs-5" %>
    <% if @posts.empty? %>
      <h3 class="text-danger my-4">Nie ma aktualnie żadnych postów...</h3>
    <% end %>
  </div>

  <%= render @posts %>

</div>

app/views/admin/posts/myposts.html.erb
<div class="container" style="font-family: 'Peralta', cursive;">
  <div class="text-center my-3">
    <h1 class="d-inline">Moje wpisy</h1>
    <%= link_to " + Dodaj nowy", new_admin_post_path, class:"btn btn-warning d-inline float-end fs-5" %>
  </div>
  <% if @myposts.empty? %>
    <h3 class="text-center text-danger my-4">Nie masz jeszcze żadnych postów na swoim koncie!</h3>
  <% else %>
    <%=  render @myposts %>
  <% end %>
</div>

app/views/admin/posts/new.html.erb
<div class="container my-4" style="font-family: 'Peralta', cursive; width: 900px;">
  <div class="card text-center">
    <div class="card-header bg-primary text-black bg-gradien fs-2">
      <h1> Your new Post </h1>
    </div>
    <%= render "form", post: @post %>
  </div>
</div>

app/views/admin/posts/show.html.erb
<br>
<div class="container" style="font-family: 'Peralta', cursive;">
  <div class="card border border-primary">
    <div class="card-header text-black bg-primary bg-gradien">
      <h1 class="d-inline text-white mx-4">
        <%= @post.title %>
      </h1>

      <p class="d-inline float-end fs-4 text-white mx-4 my-2">
        <%= @post.post_date.strftime("%k:%M %d/%m/%Y") %>
      </p>
      <p class="d-inline float-end fs-4 text-white mx-4 my-2">
        <%= User.find(@post.user_id).nick %>
      </p>
    </div>
    <div class="card-body">
      <p class="card-text fs-5">
        <%= @post.content %>
      </p>
      <div class="btn-group float-end" role="group" >
        <% if user_signed_in? && current_user.id == @post.user_id %>
          <%= link_to "Edytuj Post", edit_post_path(@post), class:"btn btn-warning float-end fs-6" %>
          <%= link_to "Usuń", post_path(@post), class:"btn btn-warning float-end fs-6", data: {
                              turbo_method: :delete,
                              turbo_confirm: "Na pewno?"
                              } %>
        <% end %>
        <%= link_to "Pdf", post_path(id: @post.id, format: :pdf), class:"btn btn-warning float-end fs-6" %>

      </div>
    </div>

    <% if !@post.comments.empty? %>
    <ul class="list-group list-group-flush bg-primary bg-gradien ">
      <h3 class="text-white my-3 mx-3 text-dark">Komentarze</h3>
      <li class="list-group-item bg-gradien">
        <%= render @post.comments %>
      </li>
    </ul>
    <% end %>
    <div class="container-flex">
      <% if user_signed_in? %>
        <%= render 'admin/comments/form' %>
      <% else %>
        <p class="fs-4 text-white my-2"> Aby dodać komentarz trzeba się zalogować! </p>
      <% end %>
    </div>

  </div>
</div>
<br>

app/views/comments/_comment.html.erb
<div class="card my-3 border border-primary">
  <div class="card-body">
    <h4 class="card-title text-muted d-inline ">
      <%= User.find(comment.user_id).nick %>
    </h4>
    <h4 class="text-muted float-end d-inline">
      <%= comment.comment_date.strftime("%k:%M %d/%m/%Y") %>
    </h4>
    <p class="card-text my-3">
      <%= comment.content %>
    </p>

    <% if user_signed_in? && current_user.id == comment.user_id %>
      <%= link_to "Usuń komentarz", [comment.post, comment],class:"btn btn-warning float-end fs-6", data: {
                      turbo_method: :delete,
                      turbo_confirm: "Na pewno?"
                    } %>
    <% end %>
  </div>
</div>
<br>

app/views/comments/_form.html.erb
<%= form_with model: [ @post, @post.comments.build ] do |f| %>

    <div class="d-flex justify-content-center">
      <%= f.text_area :content, size:"80x4", class:"form-control", placeholder: "Komentarz" %>
    </div>
      <%= f.number_field :user_id, id: :post_user_id, class:"form-control", value: current_user.id, type: :hidden%>
    <div class="text-center">
      <%= f.submit "Dodaj komentarz", class:"btn btn-warning fs-6 my-2" %>
    </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>My Blog</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "http://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css"%>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Peralta&family=Permanent+Marker&display=swap" rel="stylesheet">
    </head>
  <body>
    <script src="http://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <div>
      <%= render 'My_blog/header' %>
    </div>
    <% if notice %>
      <div class=" container alert alert-success alert-dismissible fade show my-3" role="alert">
        <strong><%= notice %></strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      <% end %>
    <% if alert %>
    <div class="container alert alert-danger alert-dismissible fade show my-3" role="alert">
      <strong><%= alert %></strong>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>My Blog</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag "http://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css"%>
    <%= wicked_pdf_stylesheet_link_tag "bootstrap" %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Peralta&family=Permanent+Marker&display=swap" rel="stylesheet">
    </head>
  <body>
    <% if notice %>
      <div class=" container alert alert-success alert-dismissible fade show my-3" role="alert">
        <strong><%= notice %></strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      <% end %>
    <% if alert %>
    <div class="container alert alert-danger alert-dismissible fade show my-3" role="alert">
      <strong><%= alert %></strong>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="card" style="font-family: 'Peralta', cursive;">
  <div class="card-header bg-primary bg-gradien fs-3 text-white">
    <%= post.title %>
  </div>
  <div class="card-body">
    <p class="card-text fs-5">
      <%= post.content %>
    </p>
  </div>
  <div class="card-footer text-muted">
    <p class="d-inline mx-3 fs-5">
      <%= User.find(post.user_id).nick %>
    </p>
    <p class="d-inline mx-3 fs-5">
      <%= post.post_date.strftime("%k:%M %d/%m/%Y") %>
    </p>

    <%= link_to "Wiecej...", post_path(post.id), class:"d-inline btn btn-warning float-end fs-6" %>
  </div>
</div>
<br>

app/views/posts/index.html.erb
<div class="container" style="font-family: 'Peralta', cursive;">
  <div class="my-3">
    <h1 class="d-inline">Aktualne Wpisy</h1>
    <% if @posts.empty? %>
      <h3 class="text-danger my-4">Nie ma aktualnie żadnych postów...</h3>
    <% end %>

  </div>

  <%= render @posts %>

</div>

app/views/posts/show.html.erb
<br>
<div class="container" style="font-family: 'Peralta', cursive;">
  <div class="card border border-primary">
    <div class="card-header text-black bg-primary bg-gradien">
      <h1 class="d-inline text-white mx-4">
        <% @post.title %>
      </h1>

      <p class="d-inline float-end fs-4 text-white mx-4 my-2">
        <%= @post.post_date.strftime("%k:%M %d/%m/%Y") %>
      </p>
      <p class="d-inline float-end fs-4 text-white mx-4 my-2">
        <%= User.find(@post.user_id).nick %>
      </p>
    </div>
    <div class="card-body">
      <p class="card-text fs-5">
        <%= @post.content %>
      </p>
      <div class="btn-group float-end" role="group" >
        <% if user_signed_in? && current_user.id == @post.user_id %>
          <%= link_to "Edytuj Post", edit_post_path(@post), class:"btn btn-warning float-end fs-6" %>
          <%= link_to "Usuń", post_path(@post), class:"btn btn-warning float-end fs-6", data: {
                              turbo_method: :delete,
                              turbo_confirm: "Na pewno?"
                              } %>
        <% end %>
        <%= link_to "Pdf", post_path(id: @post.id, format: :pdf), class:"btn btn-warning float-end fs-6" %>
      </div>
    </div>

    <% if !@post.comments.empty? %>
    <ul class="list-group list-group-flush bg-primary bg-gradien ">
      <h3 class="text-white my-3 mx-3 text-dark">Komentarze</h3>
      <li class="list-group-item bg-gradien">
        <%= render @post.comments %>
      </li>
    </ul>
    <% end %>
    <div class="container-flex">
      <% if user_signed_in? %>
        <%= render 'comments/form' %>
      <% else %>
        <p class="fs-4 text-center text-primary my-2"> Aby dodać komentarz trzeba się zalogować! </p>
      <% end %>
    </div>

  </div>
</div>
<br>